[package]
name = "local-deps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
i-haz-deps = { version = "0.1.0", path = "../i-haz-deps" }
rand = "0.8.5"
